name: Quality Assurance

on:
  - push

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout
    - uses: swift-actions/setup-swift@v2
      name: Setup Swift
      with:
        swift-version: '5.10.1'
    - name: Setup dependencies
      run: make setup
    - name: Setup linters
      run: brew install swiftlint shellcheck
    - name: Check build
      run: make build
    - name: Check code style
      run: make lint
    - name: Run tests
      run: make test
